version: "3.4"

volumes:
    web_data:

services:
    app:
        image: nginx:alpine
        ports:
            - 7788:80
        volumes:
            - web_data:/usr/share/nginx/html:ro
  
    cow:
        image: bambeeh/hakap1:latest
        volumes:
            - web_data:/root/html
